name: automatic_phone_silencer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  flutter_local_notifications: ^17.1.2
  permission_handler: ^10.0.0
  flutter_sms: ^2.3.2
  timezone: ^0.9.3
  google_maps_flutter: ^2.2.2
  geolocator: ^8.2.0
  geocoding: ^2.0.5
  intl: ^0.17.0
  sound_mode: ^3.0.0
  flutter_ringtone_player: ^3.0.0
  flutter_picker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.0.17

flutter:
  uses-material-design: true
